spring:
  #链路追踪服务端地址
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
####spring####

####eureka####
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8751/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
####eureka####
####zuul####
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    #默认整合ribbon，自动开启负载均衡轮循效果
    api-user:
      path: /user/**
      serviceId: user-service
    api-order:
      path: /order/**
      serviceId: order-service
####zuul####
####actuator####
#开启所有监控中心接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
####actuator####

####ribbon####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
####ribbon####

####hystrix####
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
####hystrix####