server:
  port: 8086

spring:
  application:
    #读取的版本环境
    name: admin-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8751/eureka/,http://localhost:8761/eureka/
    #开启健康检查（需要spring-boot-starter-actuator依赖）
    healthcheck:
      enabled: true